Build resolved fix
Solution URL:    https://github.com/microsoft/monaco-editor-webpack-plugin/issues/91#issuecomment-568862457

Error: 

> react-jsonschema-form@1.8.2 build:dist
> rimraf dist && cross-env NODE_ENV=production webpack --config webpack.config.dist.js

/usr/share/nginx/html/jssaints/react-jsonschema-form/node_modules/webpack-cli/bin/cli.js:281
				throw err;
				^

Error: Cannot find module 'vs/editor/contrib/gotoSymbol/goToCommands'
Require stack:
- /usr/share/nginx/html/jssaints/react-jsonschema-form/node_modules/monaco-editor-webpack-plugin/out/index.js
- /usr/share/nginx/html/jssaints/react-jsonschema-form/webpack.config.dist.js
- /usr/share/nginx/html/jssaints/react-jsonschema-form/node_modules/webpack-cli/bin/utils/convert-argv.js
- /usr/share/nginx/html/jssaints/react-jsonschema-form/node_modules/webpack-cli/bin/cli.js
- /usr/share/nginx/html/jssaints/react-jsonschema-form/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (/usr/share/nginx/html/jssaints/react-jsonschema-form/node_modules/v8-compile-cache/v8-compile-cache.js:164:23)
    at resolveMonacoPath (/usr/share/nginx/html/jssaints/react-jsonschema-form/node_modules/monaco-editor-webpack-plugin/out/index.js:34:28)
    at /usr/share/nginx/html/jssaints/react-jsonschema-form/node_modules/monaco-editor-webpack-plugin/out/index.js:173:63